// <auto-generated />
using System;
using CaseManagement.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CaseManagement.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261006101049_OpenCaseIndexes")]
    partial class OpenCaseIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CaseManagement.Api.Models.AgentSkill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ProficiencyLevel")
                        .HasColumnType("integer");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "SkillName")
                        .IsUnique();

                    b.ToTable("AgentSkills");
                });

            modelBuilder.Entity("CaseManagement.Api.Models.AssignmentConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Algorithm")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxConcurrentCapacity")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId")
                        .IsUnique()
                        .HasFilter("\"DepartmentId\" IS NOT NULL");

                    b.ToTable("AssignmentConfigurations");
                });

            modelBuilder.Entity("CaseManagement.Api.Models.BusinessCalendarSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("BusinessCalendarSettings");
                });

            modelBuilder.Entity("CaseManagement.Api.Models.BusinessHour", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("interval");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("interval");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DayOfWeek")
                        .IsUnique();

                    b.ToTable("BusinessHours");
                });

            modelBuilder.Entity("CaseManagement.Api.Models.Case", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CaseNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CaseType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CommunicationChannel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Disposition")
                        .HasColumnType("text");

                    b.Property<int>("EscalationLevel")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ExternalResolutionDueAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ExternalResolutionTargetMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FirstResponseActualAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FirstResponseDueAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstResponseStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FirstResponseTargetMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("InternalResolutionDueAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("InternalResolutionTargetMinutes")
                        .HasColumnType("integer");

                    b.Property<Guid?>("LinkedSourceCaseId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentCaseId")
                        .HasColumnType("uuid");

                    b.Property<string>("PreferredCommunicationChannel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResolutionNote")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("SlaBreachedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SlaConfigVersion")
                        .HasColumnType("integer");

                    b.Property<string>("SlaOutcome")
                        .HasColumnType("text");

                    b.Property<DateTime?>("SlaPausedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("SlaReminderSent")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("SlaStartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SlaTargetHours")
                        .HasColumnType("integer");

                    b.Property<int>("SlaTotalPausedMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("SourceChannel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SubcaseType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Subcategory")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CaseNumber")
                        .IsUnique();

                    b.HasIndex("CreatedAt")
                        .IsDescending();

                    b.HasIndex("CustomerId");

                    b.HasIndex("LinkedSourceCaseId");

                    b.HasIndex("ParentCaseId");

                    b.HasIndex("Severity");

                    b.HasIndex("SlaOutcome")
                        .HasDatabaseName("IX_Cases_SlaOutcome_Breached")
                        .HasFilter("\"SlaOutcome\" = 'Breached'");

                    b.HasIndex("SlaStartTime")
                        .HasDatabaseName("IX_Cases_Open_SlaStart")
                        .HasFilter("\"Status\" NOT IN ('Resolved', 'Closed', 'Cancelled')");

                    b.HasIndex("DepartmentId", "CreatedAt")
                        .IsDescending(false, true);

                    b.HasIndex("DepartmentId", "Status")
                        .HasDatabaseName("IX_Cases_Open_Department")
                        .HasFilter("\"Status\" NOT IN ('Resolved', 'Closed', 'Cancelled')");

                    b.HasIndex("OwnerId", "Status")
                        .HasDatabaseName("IX_Cases_Open_Owner")
                        .HasFilter("\"Status\" NOT IN ('Resolved', 'Closed', 'Cancelled')");

                    b.HasIndex("Status", "CreatedAt")
                        .IsDescending(false, true);

                    b.ToTable("Cases");
                });

            modelBuilder.Entity("CaseManagement.Api.Models.CaseAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentHash")
                        .HasColumnType("text");

                    b.Property<string>("ContentType")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.HasIndex("UploadedByUserId");

                    b.ToTable("CaseAttachments");
                });

            modelBuilder.Entity("CaseManagement.Api.Models.CaseChildRelation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChildId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LinkedCaseId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ParentCaseId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RelationType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ChildId")
                        .IsUnique();

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("LinkedCaseId");

                    b.HasIndex("ParentCaseId");

                    b.ToTable("CaseChildRelations");
                });

            modelBuilder.Entity("CaseManagement.Api.Models.CaseCollaborationActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("TargetUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("TargetUserId");

                    b.HasIndex("CaseId", "CreatedAt")
                        .IsDescending(false, true);

                    b.ToTable("CaseCollaborationActivities");
                });

            modelBuilder.Entity("CaseManagement.Api.Models.CaseCustomAttribute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FieldKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FieldValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CaseId", "FieldKey")
                        .IsUnique();

                    b.ToTable("CaseCustomAttributes");
                });

            modelBuilder.Entity("CaseManagement.Api.Models.CaseEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActionType")
                        .HasColumnType("text");

                    b.Property<Guid?>("CaseId")
                        .HasColumnType("uuid");

                    b.Property<string>("Channel")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EntityName")
                        .HasColumnType("text");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsInternal")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Module")
                        .HasColumnType("text");

                    b.Property<string>("NewValue")
                        .HasColumnType("text");

                    b.Property<string>("OldValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .IsDescending();

                    b.HasIndex("UserId");

                    b.HasIndex("CaseId", "CreatedAt")
                        .IsDescending(false, true);

                    b.ToTable("CaseEvents");
                });

            modelBuilder.Entity("CaseManagement.Api.Models.CaseParticipant", b =>
                {
                    b.Property<Guid>("CaseId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CaseId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("CaseParticipants");
                });

            modelBuilder.Entity("CaseManagement.Api.Models.CaseTypeConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("CaseTypeConfigs");
                });

            modelBuilder.Entity("CaseManagement.Api.Models.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountNumber")
                        .HasColumnType("text");

                    b.Property<string>("Branch")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerSegment")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IdType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("NRIC Number");

                    b.Property<string>("NRIC")
                        .HasColumnType("text");

                    b.Property<string>("Passport")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AccountNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_Customers_AccountNumber_Unique")
                        .HasFilter("\"AccountNumber\" IS NOT NULL AND \"AccountNumber\" <> ''");

                    b.HasIndex("NRIC")
                        .IsUnique()
                        .HasDatabaseName("IX_Customers_NRIC_Unique")
                        .HasFilter("\"NRIC\" IS NOT NULL AND \"NRIC\" <> ''");

                    b.HasIndex("Passport")
                        .IsUnique()
                        .HasDatabaseName("IX_Customers_Passport_Unique")
                        .HasFilter("\"Passport\" IS NOT NULL AND \"Passport\" <> ''");

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_Customers_PhoneNumber_Unique")
                        .HasFilter("\"PhoneNumber\" IS NOT NULL AND \"PhoneNumber\" <> ''");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("CaseManagement.Api.Models.CustomerCustomAttribute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("FieldKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FieldValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("CustomerCustomAttributes");
                });

            modelBuilder.Entity("CaseManagement.Api.Models.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Function")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("OwnerId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("CaseManagement.Api.Models.DepartmentSubCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("DepartmentSubCategories");
                });

            modelBuilder.Entity("CaseManagement.Api.Models.EscalationLevelConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActionDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AssignmentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("LevelNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("ReassignOwner")
                        .HasColumnType("boolean");

                    b.Property<string>("TargetRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TargetUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("TriggerDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TriggerType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("TriggerValue")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LevelNumber")
                        .IsUnique();

                    b.HasIndex("TargetUserId");

                    b.ToTable("EscalationLevelConfigs");
                });

            modelBuilder.Entity("CaseManagement.Api.Models.FieldConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApiField")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayLabel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("FieldType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsCustomField")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEditable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSensitive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSystemRequired")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("boolean");

                    b.Property<string>("LookupTypeCode")
                        .HasColumnType("text");

                    b.Property<string>("MaskingRule")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("MaxLength")
                        .HasColumnType("integer");

                    b.Property<int?>("MinLength")
                        .HasColumnType("integer");

                    b.Property<string>("ModuleKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SectionKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ValidationMessage")
                        .HasColumnType("text");

                    b.Property<string>("ValidationRegex")
                        .HasColumnType("text");

                    b.Property<int>("VisibleChars")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ModuleKey", "SectionKey", "ApiField")
                        .IsUnique();

                    b.ToTable("FieldConfigurations");
                });

            modelBuilder.Entity("CaseManagement.Api.Models.LinkedCase", b =>
                {
                    b.Property<Guid>("CaseId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TargetCaseId")
                        .HasColumnType("uuid");

                    b.HasKey("CaseId", "TargetCaseId");

                    b.HasIndex("TargetCaseId");

                    b.ToTable("LinkedCases");
                });

            modelBuilder.Entity("CaseManagement.Api.Models.LookupType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("LookupTypes");
                });

            modelBuilder.Entity("CaseManagement.Api.Models.LookupValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("LookupTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("TypeCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TypeCode");

                    b.HasIndex("LookupTypeId", "Value")
                        .IsUnique();

                    b.ToTable("LookupValues");
                });

            modelBuilder.Entity("CaseManagement.Api.Models.NotificationItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CaseId")
                        .HasColumnType("uuid");

                    b.Property<string>("CaseNumber")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventKey")
                        .HasColumnType("text");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastReminderAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RecipientUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("ReminderCount")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RecipientUserId")
                        .HasDatabaseName("IX_Notifications_Unread")
                        .HasFilter("\"IsRead\" = false");

                    b.HasIndex("RecipientUserId", "CreatedAt")
                        .IsDescending(false, true);

                    b.HasIndex("RecipientUserId", "EventKey")
                        .IsUnique()
                        .HasDatabaseName("UX_Notifications_Recipient_EventKey")
                        .HasFilter("\"EventKey\" IS NOT NULL");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("CaseManagement.Api.Models.PriorityCategoryMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DepartmentSubCategoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PrioritySlaRuleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentSubCategoryId")
                        .IsUnique();

                    b.HasIndex("PrioritySlaRuleId");

                    b.ToTable("PriorityCategoryMappings");
                });

            modelBuilder.Entity("CaseManagement.Api.Models.PrioritySlaRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<int>("ExternalResolutionMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("ExternalResolutionUnit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ExternalResolutionValue")
                        .HasColumnType("integer");

                    b.Property<int>("FirstResponseMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("FirstResponseUnit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FirstResponseValue")
                        .HasColumnType("integer");

                    b.Property<int>("InternalResolutionMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("InternalResolutionUnit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("InternalResolutionValue")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Priority")
                        .IsUnique();

                    b.ToTable("PrioritySlaRules");
                });

            modelBuilder.Entity("CaseManagement.Api.Models.PublicHoliday", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("HolidayDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("HolidayDate")
                        .IsUnique();

                    b.ToTable("PublicHolidays");
                });

            modelBuilder.Entity("CaseManagement.Api.Models.RoutingRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActionDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConditionsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EvaluationOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TargetDepartmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EvaluationOrder");

                    b.HasIndex("TargetDepartmentId");

                    b.ToTable("RoutingRules");
                });

            modelBuilder.Entity("CaseManagement.Api.Models.SeedHistoryEntry", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("AppliedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Key");

                    b.ToTable("SeedHistory", (string)null);
                });

            modelBuilder.Entity("CaseManagement.Api.Models.SkillRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("MatchField")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MatchType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MatchValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("SkillRules");
                });

            modelBuilder.Entity("CaseManagement.Api.Models.TeamAssignmentPointer", b =>
                {
                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastAssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LastAssignedUserId")
                        .HasColumnType("uuid");

                    b.HasKey("DepartmentId");

                    b.HasIndex("LastAssignedUserId");

                    b.ToTable("TeamAssignmentPointers");
                });

            modelBuilder.Entity("CaseManagement.Api.Models.TeamMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsAssignable")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MemberRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("DepartmentId", "UserId")
                        .IsUnique();

                    b.ToTable("TeamMembers");
                });

            modelBuilder.Entity("CaseManagement.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExternalUserId")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Queue")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Team")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("ExternalUserId")
                        .IsUnique()
                        .HasFilter("\"ExternalUserId\" IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CaseManagement.Api.Models.AgentSkill", b =>
                {
                    b.HasOne("CaseManagement.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CaseManagement.Api.Models.AssignmentConfiguration", b =>
                {
                    b.HasOne("CaseManagement.Api.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Department");
                });

            modelBuilder.Entity("CaseManagement.Api.Models.Case", b =>
                {
                    b.HasOne("CaseManagement.Api.Models.Customer", "Customer")
                        .WithMany("Cases")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CaseManagement.Api.Models.Department", "Department")
                        .WithMany("Cases")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CaseManagement.Api.Models.Case", "LinkedSourceCase")
                        .WithMany()
                        .HasForeignKey("LinkedSourceCaseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CaseManagement.Api.Models.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CaseManagement.Api.Models.Case", "ParentCase")
                        .WithMany("Subcases")
                        .HasForeignKey("ParentCaseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Customer");

                    b.Navigation("Department");

                    b.Navigation("LinkedSourceCase");

                    b.Navigation("Owner");

                    b.Navigation("ParentCase");
                });

            modelBuilder.Entity("CaseManagement.Api.Models.CaseAttachment", b =>
                {
                    b.HasOne("CaseManagement.Api.Models.Case", "Case")
                        .WithMany("Attachments")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CaseManagement.Api.Models.User", "UploadedByUser")
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Case");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("CaseManagement.Api.Models.CaseChildRelation", b =>
                {
                    b.HasOne("CaseManagement.Api.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CaseManagement.Api.Models.Case", "LinkedCase")
                        .WithMany()
                        .HasForeignKey("LinkedCaseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CaseManagement.Api.Models.Case", "ParentCase")
                        .WithMany("ChildRelations")
                        .HasForeignKey("ParentCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("LinkedCase");

                    b.Navigation("ParentCase");
                });

            modelBuilder.Entity("CaseManagement.Api.Models.CaseCollaborationActivity", b =>
                {
                    b.HasOne("CaseManagement.Api.Models.User", "ActorUser")
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CaseManagement.Api.Models.Case", "Case")
                        .WithMany()
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CaseManagement.Api.Models.User", "TargetUser")
                        .WithMany()
                        .HasForeignKey("TargetUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ActorUser");

                    b.Navigation("Case");

                    b.Navigation("TargetUser");
                });

            modelBuilder.Entity("CaseManagement.Api.Models.CaseCustomAttribute", b =>
                {
                    b.HasOne("CaseManagement.Api.Models.Case", "Case")
                        .WithMany("CustomAttributes")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("CaseManagement.Api.Models.CaseEvent", b =>
                {
                    b.HasOne("CaseManagement.Api.Models.Case", "Case")
                        .WithMany("Events")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CaseManagement.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Case");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CaseManagement.Api.Models.CaseParticipant", b =>
                {
                    b.HasOne("CaseManagement.Api.Models.Case", "Case")
                        .WithMany("Participants")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CaseManagement.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CaseManagement.Api.Models.CustomerCustomAttribute", b =>
                {
                    b.HasOne("CaseManagement.Api.Models.Customer", "Customer")
                        .WithMany("CustomAttributes")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CaseManagement.Api.Models.Department", b =>
                {
                    b.HasOne("CaseManagement.Api.Models.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("CaseManagement.Api.Models.DepartmentSubCategory", b =>
                {
                    b.HasOne("CaseManagement.Api.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("CaseManagement.Api.Models.EscalationLevelConfig", b =>
                {
                    b.HasOne("CaseManagement.Api.Models.User", "TargetUser")
                        .WithMany()
                        .HasForeignKey("TargetUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("TargetUser");
                });

            modelBuilder.Entity("CaseManagement.Api.Models.LinkedCase", b =>
                {
                    b.HasOne("CaseManagement.Api.Models.Case", "Case")
                        .WithMany("LinkedCases")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CaseManagement.Api.Models.Case", "TargetCase")
                        .WithMany("LinkedToCases")
                        .HasForeignKey("TargetCaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Case");

                    b.Navigation("TargetCase");
                });

            modelBuilder.Entity("CaseManagement.Api.Models.LookupValue", b =>
                {
                    b.HasOne("CaseManagement.Api.Models.LookupType", "LookupType")
                        .WithMany("Values")
                        .HasForeignKey("LookupTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LookupType");
                });

            modelBuilder.Entity("CaseManagement.Api.Models.NotificationItem", b =>
                {
                    b.HasOne("CaseManagement.Api.Models.User", "RecipientUser")
                        .WithMany()
                        .HasForeignKey("RecipientUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecipientUser");
                });

            modelBuilder.Entity("CaseManagement.Api.Models.PriorityCategoryMapping", b =>
                {
                    b.HasOne("CaseManagement.Api.Models.DepartmentSubCategory", "DepartmentSubCategory")
                        .WithMany()
                        .HasForeignKey("DepartmentSubCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CaseManagement.Api.Models.PrioritySlaRule", "PrioritySlaRule")
                        .WithMany("CategoryMappings")
                        .HasForeignKey("PrioritySlaRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DepartmentSubCategory");

                    b.Navigation("PrioritySlaRule");
                });

            modelBuilder.Entity("CaseManagement.Api.Models.RoutingRule", b =>
                {
                    b.HasOne("CaseManagement.Api.Models.Department", "TargetDepartment")
                        .WithMany()
                        .HasForeignKey("TargetDepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TargetDepartment");
                });

            modelBuilder.Entity("CaseManagement.Api.Models.TeamAssignmentPointer", b =>
                {
                    b.HasOne("CaseManagement.Api.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CaseManagement.Api.Models.User", "LastAssignedUser")
                        .WithMany()
                        .HasForeignKey("LastAssignedUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("LastAssignedUser");
                });

            modelBuilder.Entity("CaseManagement.Api.Models.TeamMember", b =>
                {
                    b.HasOne("CaseManagement.Api.Models.Department", "Department")
                        .WithMany("Members")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CaseManagement.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CaseManagement.Api.Models.User", b =>
                {
                    b.HasOne("CaseManagement.Api.Models.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("CaseManagement.Api.Models.Case", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("ChildRelations");

                    b.Navigation("CustomAttributes");

                    b.Navigation("Events");

                    b.Navigation("LinkedCases");

                    b.Navigation("LinkedToCases");

                    b.Navigation("Participants");

                    b.Navigation("Subcases");
                });

            modelBuilder.Entity("CaseManagement.Api.Models.Customer", b =>
                {
                    b.Navigation("Cases");

                    b.Navigation("CustomAttributes");
                });

            modelBuilder.Entity("CaseManagement.Api.Models.Department", b =>
                {
                    b.Navigation("Cases");

                    b.Navigation("Members");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("CaseManagement.Api.Models.LookupType", b =>
                {
                    b.Navigation("Values");
                });

            modelBuilder.Entity("CaseManagement.Api.Models.PrioritySlaRule", b =>
                {
                    b.Navigation("CategoryMappings");
                });
#pragma warning restore 612, 618
        }
    }
}
